# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=120)),
                ('vehicle_number', models.CharField(max_length=120)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('scheduled', 'Scheduled')], max_length=120, null=True)),
                ('running', models.BooleanField(default=False)),
                ('stopped', models.BooleanField(default=False)),
                ('scheduled', models.BooleanField(default=False)),
                ('start_time', models.TimeField()),
                ('last_update', models.TimeField()),
                ('last_stoppage', models.CharField(max_length=120)),
            ],
        ),
    ]
