# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='running',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='scheduled',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='stopped',
        ),
    ]
